// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApgmI_dBiKqWCGevmKjZ-Iaucjr6BmfM0',
    appId: '1:703221889400:web:44bdc6e0c867dac2db708d',
    messagingSenderId: '703221889400',
    projectId: 'fct-zaitec-medac',
    authDomain: 'fct-zaitec-medac.firebaseapp.com',
    storageBucket: 'fct-zaitec-medac.firebasestorage.app',
    measurementId: 'G-GNNSQ6LY7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYNsNeg0nLfL6TLt6Fj8yo1TyduLiutq8',
    appId: '1:703221889400:android:8e6186c372a49654db708d',
    messagingSenderId: '703221889400',
    projectId: 'fct-zaitec-medac',
    storageBucket: 'fct-zaitec-medac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7IjNxU_aavt6gXZAb8k9vu_hDcD6HJ7k',
    appId: '1:703221889400:ios:3eb1c5eff7b410bddb708d',
    messagingSenderId: '703221889400',
    projectId: 'fct-zaitec-medac',
    storageBucket: 'fct-zaitec-medac.firebasestorage.app',
    iosBundleId: 'com.example.fctInventario2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7IjNxU_aavt6gXZAb8k9vu_hDcD6HJ7k',
    appId: '1:703221889400:ios:3eb1c5eff7b410bddb708d',
    messagingSenderId: '703221889400',
    projectId: 'fct-zaitec-medac',
    storageBucket: 'fct-zaitec-medac.firebasestorage.app',
    iosBundleId: 'com.example.fctInventario2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApgmI_dBiKqWCGevmKjZ-Iaucjr6BmfM0',
    appId: '1:703221889400:web:04f3dd1b583972e7db708d',
    messagingSenderId: '703221889400',
    projectId: 'fct-zaitec-medac',
    authDomain: 'fct-zaitec-medac.firebaseapp.com',
    storageBucket: 'fct-zaitec-medac.firebasestorage.app',
    measurementId: 'G-0KD279Z67T',
  );
}
